.NET change
livepvrdata-oss/livepvrdata-clients pull request #1
Opened 2016-09-18 20:23 UTC by emveepee

Changes for local run and API change

2016-09-18 20:33 UTC, Slugger commented on dotnet/trunk/LivePvrDataDotNet/Client.cs
> +                payload = clnt.UploadString(uri + "livepvrdata/query", "q=" + HttpUtility.UrlEncode(serializer.Serialize(req)));
You're assuming the deployed app context, which I don't think is correct.  It should be just `query`, which is relative and should automatically deduce the deployed context based on the base uri being used.  You could probably mod the default uri to be `localhost:8080/livepvrdata` if the default context is livepvrdata (I don't remember if that's the case).  Either way, hardcoding the app context here is not a great idea.

2016-09-18 20:33 UTC, Slugger requested changes
Hardcoding of app context not best idea.

2016-09-18 20:41 UTC, emveepee commented
If I change it to query, then  the user has to pass

http://ip:port/livepvrdata to override the default.  That seems confusing to me.

2016-09-18 20:52 UTC, Slugger commented
The problem with hardcoding the context here is that your client is no good -- and can't be reconfigured at runtime -- for use against a server that doesn't deploy to the hardcoded context you've specified here.

For example, when I ran the service on Google, I just ran it from the default context, which is why the default url was just `www.livepvrdata.com/` and to do a query you'd have to hit `www.livepvrdata.com/query`.  With your change here, you're assuming every instance of the service will always deploy to a context named `livepvrdata` and if a service deployment doesn't, your client is no good and will never be able to query it.  Assuming an app context is never a good idea.

2016-09-18 20:59 UTC, Slugger commented
But, as I said, if you want to include `livepvrdata` as the default context in the `DEFAULT_URI` then that would be fine.  And that probably even makes sense since I'm assuming you did this because the service will deploy to `livepvrdata` by default.

2016-09-19 00:02 UTC, emveepee commented
Not including the context in the default was my concern confusion, I have modified the pull request as suggested.  Thanks

2016-09-19 00:24 UTC, Slugger approved these changes

2016-09-19 00:25 UTC, merged

2016-09-19 00:27 UTC, Slugger commented
Merged this PR.  I assume you tested the changes, my naked eye thinks there might be a missing slash in the url when using the `DEFAULT_URI` as the base uri, but if you tested it then I'm wrong and that's fine.  If I happen to be right, you'll find out soon enough and can just submit another PR. ;)

2016-09-19 00:41 UTC, emveepee commented
Yes there is a missing / because my code overrides the default.    I was just going to do an update.

Martin